#!/usr/bin/env bash
# Detect what we are running on and record it in state/detected.env, which every
# later script reads so none of them has to guess.
. "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

step "Preflight"

MODEL="$(pi_model)"
OS_CODENAME="$(os_codename)"
OS_PRETTY="$( { . /etc/os-release && echo "$PRETTY_NAME"; } 2>/dev/null || echo unknown )"
ARCH="$(uname -m)"
KERNEL="$(uname -r)"
COMPOSITOR="$(detect_compositor)"

# A desktop image ships the Pi panel; Lite does not. Drives whether the desktop
# theming scripts have anything to do.
if [ -d /usr/share/themes ] && { has_cmd wf-panel-pi || has_cmd pcmanfm || [ -d /usr/share/themes/PiXflat ]; }; then
	HAS_DESKTOP=1
else
	HAS_DESKTOP=0
fi

ROOT_SRC="$(findmnt -no SOURCE / 2>/dev/null || echo unknown)"
BOOT_SRC="$(findmnt -no SOURCE /boot/firmware 2>/dev/null || echo none)"

# Whole-disk device backing a partition, e.g. /dev/sda2 -> sda, /dev/nvme0n1p2 -> nvme0n1.
disk_of() {
	local part="${1#/dev/}"
	lsblk -no PKNAME "/dev/$part" 2>/dev/null | head -n1 || true
}
ROOT_DISK="$(disk_of "$ROOT_SRC")"

# Is there a real NVMe device on the PCIe bus? Only then is PCIe tuning relevant.
if [ -e /dev/nvme0n1 ] || { has_cmd lspci && lspci 2>/dev/null | grep -qi 'non-volatile memory'; }; then
	HAS_NVME=1
else
	HAS_NVME=0
fi

# The HAT SSD is the largest disk that is not the one we booted from.
EXTRA_DISK=""
EXTRA_DISK_TRAN=""
if has_cmd lsblk; then
	while read -r name size tran type; do
		[ "$type" = "disk" ] || continue
		[ "$name" = "$ROOT_DISK" ] && continue
		case "$name" in mmcblk*|zram*|loop*|ram*) continue ;; esac
		if [ -z "$EXTRA_DISK" ]; then EXTRA_DISK="$name"; EXTRA_DISK_TRAN="$tran"; fi
		log "extra disk: /dev/$name  $size  ${tran:-?}"
	done < <(lsblk -dnr -o NAME,SIZE,TRAN,TYPE 2>/dev/null)
fi

log "model:       $MODEL"
log "os:          $OS_PRETTY ($OS_CODENAME, $ARCH)"
log "kernel:      $KERNEL"
log "compositor:  $COMPOSITOR"
log "desktop:     $([ "$HAS_DESKTOP" = 1 ] && echo yes || echo 'no (Lite image)')"
log "root on:     $ROOT_SRC (disk ${ROOT_DISK:-unknown})"
log "boot fw on:  $BOOT_SRC"
log "nvme found:  $([ "$HAS_NVME" = 1 ] && echo yes || echo no)"
if [ -n "$EXTRA_DISK" ]; then
	log "hat ssd:     /dev/$EXTRA_DISK (${EXTRA_DISK_TRAN:-unknown bus})"
else
	log "hat ssd:     none detected"
fi

case "$OS_CODENAME" in
	trixie|bookworm) ;;
	*) warn "untested OS '$OS_CODENAME'; scripts assume Raspberry Pi OS Bookworm or Trixie" ;;
esac
[ "$COMPOSITOR" = none ] && [ "$HAS_DESKTOP" = 1 ] && \
	warn "no labwc/wayfire found; window decoration theming will be skipped"

ensure_dir "$STATE_DIR"
write_file "$STATE_DIR/detected.env" <<ENV
# Generated by scripts/00-preflight.sh on $(date -Iseconds). Do not edit by hand.
MODEL="$MODEL"
OS_CODENAME="$OS_CODENAME"
OS_PRETTY="$OS_PRETTY"
ARCH="$ARCH"
KERNEL="$KERNEL"
COMPOSITOR="$COMPOSITOR"
HAS_DESKTOP="$HAS_DESKTOP"
ROOT_SRC="$ROOT_SRC"
ROOT_DISK="$ROOT_DISK"
BOOT_SRC="$BOOT_SRC"
HAS_NVME="$HAS_NVME"
EXTRA_DISK="$EXTRA_DISK"
EXTRA_DISK_TRAN="$EXTRA_DISK_TRAN"
TARGET_USER="$TARGET_USER"
TARGET_HOME="$TARGET_HOME"
ENV

summary "preflight"
